FROM evild/alpine-nodejs:5.7.1

MAINTAINER DOMINIQUE HAAS <contact@dominique-haas.fr>

## App dependencies
# Add the files
#ADD root/app/package.json /app/package.json
#WORKDIR /app
#RUN npm install

ADD root /
