stages:
  - test
  - tweet
  - deploy

before_script:
  - docker info

test_job:
  stage: test
  script:
    - ci/nodejs_test

tweet_succeed_job:
  variables:
    PASSED: "true"
  stage: tweet
  only:
    - tags
    - triggers
    - master
  script:
    - ci/nodejs_tweet

tweet_failed_job:
  variables:
    PASSED: "false"
  stage: tweet
  only:
    - tags
    - triggers
    - master
  script:
    - ci/nodejs_tweet
  when: on_failure

deploy_job:
  stage: deploy
  only:
    - tags
    - triggers
    - master
  script:
    - ci/nodejs_deploy
