stages:
  - build
  - build_test
  - test
  - cleanup
  - tweet
  - deploy


build_job:
  stage: build
  script:
    - ci/nodejs_build

build_test_job:
  stage: build_test
  script:
    - ci/nodejs_build_test_image

test_job:
  stage: test
  script:
    - ci/nodejs_test

cleanup:
  stage: cleanup
  script:
    - ci/nodejs_cleanup
  when: always

tweet_succeed_job:
  variables:
    PASSED: "true"
  stage: tweet
  only:
    - tags
    - triggers
    - master
  script:
    - ci/nodejs_tweet

tweet_failed_job:
  variables:
    PASSED: "false"
  stage: tweet
  only:
    - tags
    - triggers
    - master
  script:
    - ci/nodejs_tweet
  when: on_failure

deploy_job:
  stage: deploy
  only:
    - tags
    - triggers
    - master
  script:
    - ci/nodejs_deploy
