#!/bin/sh

set -e

if [ "$NIGHTLY_BUILD" ]; then
  :
else

  docker run -d --name nodejs-test-lts evild/alpine-nodejs:lts_test
  sleep 5

  if docker ps | grep -q nodejs-test-lts; then
      echo Docker nodejs-test-lts found
      if docker logs nodejs-test-lts | awk 'END{print}' | grep -q 'Hello World :)'; then
        echo Hello World found
      else
        exit
      fi
  else
      echo Docker nodejs-test-lts not found
      exit
  fi

  docker run -d --name nodejs-test-stable evild/alpine-nodejs:stable_test
  sleep 5

  if docker ps | grep -q nodejs-test-stable; then
      echo Docker nodejs-test-stable found
      if docker logs nodejs-test-stable | awk 'END{print}' | grep -q 'Hello World :)'; then
        echo Hello World found
      else
        exit
      fi
  else
      echo Docker nodejs-test-stable not found
      exit
  fi
fi
