#!/bin/sh

set -e

docker --version

if [ "$NIGHTLY_BUILD" ]; then
 :
else

docker build -t evild/alpine-nodejs:current_test ci/test_image/current
docker inspect evild/alpine-nodejs:current_test

docker build -t evild/alpine-nodejs:lts_test ci/test_image/lts
docker inspect evild/alpine-nodejs:lts_test

fi
