#!/bin/sh

set -e

docker --version

if [ "$NIGHTLY_BUILD" ]; then
  :
else

docker build -t evild/alpine-nodejs:current current
docker inspect evild/alpine-nodejs:current

docker build -t evild/alpine-nodejs:lts lts
docker inspect evild/alpine-nodejs:lts

fi
