#!/bin/sh

set -e

if [ "$NIGHTLY_BUILD" ]; then
  :
else

  docker run -d --name nodejs-test-lts evild/alpine-nodejs:lts_test
  docker ps | grep nodejs-test-lts


  docker run -d --name nodejs-test-stable evild/alpine-nodejs:stable_test
  docker ps | grep nodejs-test-stable

fi
